package Model;

public enum Permission {
    BILLING_SYSTEM,
    RETURN_AND_REFUND,
    PRODUCT_INFORMATION,
    NOTIFICATION_PANEL,
    SUPPLIER_MANAGEMENT,
    INVENTORY_MANAGEMENT,
    PERMISSION_GRANTING,
    USER_MANAGEMENT,
    PERFORMANCE_VIEW;
}
